#!/usr/bin/env bash
git clone https://github.com/bats-core/bats-core.git bats && cd bats && rm -rf .git && cd ..
mkdir -p test_helper
git clone https://github.com/bats-core/bats-support.git test_helper/bats-support && cd test_helper/bats-support && rm -rf .git && cd ../..
git clone https://github.com/bats-core/bats-assert.git test_helper/bats-assert && cd test_helper/bats-assert && rm -rf .git && cd ../..

